'use strict';
const $=id=>document.getElementById(id), KEY='bap-queue-v1', PREF='bap-queue-prefs-v1';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const pad=n=>String(n).padStart(3,'0');
let state, busy=false, context, sources=[], run=0, buffers={}, cancelWait=null, storageOK=true;
function fresh(){return {day:today(),current:0,next:1,history:[]};}
function read(){if(!storageOK&&state?.day===today())return JSON.parse(JSON.stringify(state));try{const s=JSON.parse(localStorage.getItem(KEY));if(s&&s.day===today()&&Number.isInteger(s.current)&&s.current>=0&&s.current<=999&&Number.isInteger(s.next)&&s.next>=1&&s.next<=1000&&Array.isArray(s.history)){s.history=s.history.filter(n=>Number.isInteger(n)&&n>=1&&n<=999).slice(0,6);return s;}}catch{}return fresh();}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;}catch{storageOK=false;}}
function status(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error);}
function render(){ $('number').textContent=state.current?pad(state.current):'— — —';$('nextLabel').textContent=state.next<=999?'Tiếp theo: '+pad(state.next):'Đã hết 999 số trong ngày';$('next').textContent=state.next<=999?'Gọi số tiếp theo · '+pad(state.next):'Đã đến số 999';$('next').disabled=busy||state.next>999;$('repeat').disabled=busy||!state.current;$('test').disabled=busy;$('set').disabled=busy;$('reset').disabled=busy;$('stop').disabled=!busy;$('history').replaceChildren(...state.history.map(n=>{const el=document.createElement('span');el.className='pill';el.textContent=pad(n);return el;}));if(!state.history.length)$('history').textContent='Chưa có lượt gọi';}
function syncDay(){if(state.day!==today()){stop();state=fresh();save();render();status('Ngày mới — sẵn sàng gọi số 001.');}}
function tick(){syncDay();$('clock').textContent=new Intl.DateTimeFormat('vi-VN',{timeZone:'Asia/Ho_Chi_Minh',dateStyle:'short',timeStyle:'medium'}).format(new Date());}
async function ready(){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw Error('Trình duyệt chưa hỗ trợ âm thanh. Hãy mở bằng Chrome hoặc Edge.');context??=new AC();await context.resume();if(context.state!=='running')throw Error('Chưa bật được âm thanh. Bấm “Thử loa” và kiểm tra quyền âm thanh của trang.');if(!window.QUEUE_AUDIO)throw Error('Chưa tải được bộ tiếng Việt. Kiểm tra mạng rồi tải lại trang.');await Promise.all(Object.entries(window.QUEUE_AUDIO).map(async([key,b64])=>{if(!buffers[key]){const bytes=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));buffers[key]=await context.decodeAudioData(bytes.buffer);}}));}
function stop(){run++;sources.forEach(s=>{try{s.stop();}catch{}});sources=[];if(cancelWait){cancelWait();cancelWait=null;}busy=false;render();}
function play(n,token){return new Promise(resolve=>{cancelWait=resolve;let at=context.currentTime+.08;const gain=context.createGain();gain.gain.value=Number($('volume').value)/100;gain.connect(context.destination);const keys=['prefix',...pad(n),'suffix'];let last;for(let repeat=0;repeat<Number($('times').value);repeat++){for(const key of keys){const source=context.createBufferSource();source.buffer=buffers[key];source.connect(gain);source.start(at);at+=source.buffer.duration+.06;sources.push(source);last=source;}at+=.65;}last.onended=()=>{gain.disconnect();if(token===run){sources=[];cancelWait=null;}resolve();};});}
async function call(kind){syncDay();if(busy)return;busy=true;render();const token=++run;let number=1,committed=false;try{await ready();if(token!==run)return;
 const update=()=>{state=read();if(kind==='next'){if(state.next>999)throw Error('Đã hết 999 số trong ngày.');number=state.next;state.current=number;state.next=number+1;state.history=[number,...state.history].slice(0,6);save();committed=true;}else if(kind==='repeat'){if(!state.current)throw Error('Chưa có số để gọi lại.');number=state.current;}render();};
 if(kind!=='test'){if(navigator.locks)await navigator.locks.request(KEY,update);else update();}if(token!==run)return;
 status(kind==='test'?'Đang thử loa: Xin mời số không không một.':'Đang gọi số '+pad(number)+'…');await play(number,token);if(token!==run)return;status(!storageOK?'Không lưu được số. Đừng đóng trang; hãy cho phép lưu dữ liệu trình duyệt.':kind==='test'?'Đã phát thử. Nếu nghe rõ, bạn có thể bắt đầu gọi số.':'Đã phát số '+pad(number)+'.',!storageOK);
 }catch(e){if(token===run)status(e.message+(committed?' Số đã được giữ lại; bấm “Gọi lại” để phát lại.':''),true);}finally{if(token===run){busy=false;render();}}}
$('next').onclick=()=>call('next');$('repeat').onclick=()=>call('repeat');$('test').onclick=()=>call('test');$('stop').onclick=()=>{stop();status('Đã dừng tiếng. Bấm “Gọi lại” nếu cần.');};
async function change(next){syncDay();if(busy)return;const update=()=>{state=read();state.next=next;state.current=0;state.history=[];save();render();status('Lượt tiếp theo sẽ gọi số '+pad(next)+'.');};if(navigator.locks)await navigator.locks.request(KEY,update);else update();}
$('set').onclick=()=>{const n=Number($('start').value);if(!Number.isInteger(n)||n<1||n>999){status('Nhập số nguyên từ 1 đến 999.',true);return;}if(confirm('Đặt số sẽ gọi tiếp theo là '+pad(n)+'?'))change(n);};
$('reset').onclick=()=>{if(confirm('Bắt đầu lại từ 001 trong ngày hôm nay? Việc này có thể làm trùng các số đã gọi.'))change(1);};
$('display').onclick=()=>{document.body.classList.add('display-mode');document.documentElement.requestFullscreen?.().catch(()=>{});};
function exit(){document.body.classList.remove('display-mode');if(document.fullscreenElement)document.exitFullscreen?.().catch(()=>{});}
$('exit').onclick=exit;document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement)document.body.classList.remove('display-mode');});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){stop();exit();return;}if(e.repeat||e.ctrlKey||e.altKey||e.metaKey||/INPUT|SELECT|TEXTAREA|BUTTON|SUMMARY/.test(e.target.tagName))return;if(e.key.toLowerCase()==='n'){e.preventDefault();call('next');}if(e.key.toLowerCase()==='r'){e.preventDefault();call('repeat');}});
function prefs(){ $('volText').textContent=$('volume').value+'%';try{localStorage.setItem(PREF,JSON.stringify({volume:$('volume').value,times:$('times').value}));}catch{}}
$('volume').oninput=prefs;$('times').onchange=prefs;
try{const p=JSON.parse(localStorage.getItem(PREF));if(p){$('volume').value=Math.max(10,Math.min(100,Number(p.volume)||100));$('times').value=p.times==='2'?'2':'1';$('volText').textContent=$('volume').value+'%';}}catch{}
window.addEventListener('storage',e=>{if(e.key===KEY){state=read();render();}});document.addEventListener('visibilitychange',()=>{if(!document.hidden){syncDay();state=read();render();}});
state=read();save();render();tick();setInterval(tick,1000);
